name: apple-devices
services:

  - name: api
    image:
      registry_type: GHCR
      registry_credentials: ${REGISTRY_USER}:${REGISTRY_TOKEN}
      registry: superepicstudios
      repository: apple-devices
      digest: ${API_DIGEST}

  - name: frontend
    image:
      registry_type: GHCR
      registry_credentials: ${REGISTRY_USER}:${REGISTRY_TOKEN}
      registry: superepicstudios
      repository: apple-devices
      digest: ${FRONTEND_DIGEST}
