name: Deploy (API)

# on:
#   push:
#     tags: '[0-9]+.[0-9]+.[0-9]+*'

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:

  image:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Authenticate
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Publish
        id: publish
        uses: docker/build-push-action@v6.5.0
        with:
          context: ./web/apps/api
          push: true
          tags: |
            ghcr.io/superepicstudios/apple-devices-api:latest

# ghcr.io/superepicstudios/apple-devices-api:${{ github.ref_name }}
  
  # deploy:
  #   needs: image
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy
  #       uses: digitalocean/app_action/deploy@v2
  #       with:
  #         token: ${{ secrets.DIGITALOCEAN_TOKEN }}
