name: Deploy

on:
  push:
    tags: '[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: read
  packages: write

jobs:

  publish-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: ghcr.io/superepicstudios/apple-devices-api
            dockerfile: web/apps/api/dockerfile
          - image: ghcr.io/superepicstudios/apple-devices-frontend
            dockerfile: web/apps/www/dockerfile
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Authenticate
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Publish
        id: publish
        uses: docker/build-push-action@v6.5.0
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ${{ matrix.image }}:latest
            ${{ matrix.image }}:${{ github.ref_name }}

  deploy:
    needs: publish-images
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: digitalocean/app_action/deploy@v2
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IMAGE_TAG: ${{ github.ref_name }}
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}
          app_spec_location: .do/app.yml
